### ISSUE TITLE
Specifying a meta schema in $schema forces validation error: no schema with key or ref "http://json-schema.org/draft-06/schema#"

### ISSUE THREAD

**Issue by sbusch** [rjsf-team/react-jsonschema-form#1274]
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

If the schema specifies a meta schema in `$schema`:
```javascript
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  // ...
}
```

RJSF then complains with error

    no schema with key or ref "http://json-schema.org/draft-06/schema#"

The error is issued by underlying ajv library.

### Steps to Reproduce

[Example on RJSF playground](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCJ9LCJzY2hlbWEiOnsiJHNjaGVtYSI6Imh0dHA6Ly9qc29uLXNjaGVtYS5vcmcvZHJhZnQtMDYvc2NoZW1hIyIsInRpdGxlIjoiQSByZWdpc3RyYXRpb24gZm9ybSIsImRlc2NyaXB0aW9uIjoiQSBzaW1wbGUgZm9ybSBleGFtcGxlLiIsInR5cGUiOiJvYmplY3QiLCJyZXF1aXJlZCI6WyJmaXJzdE5hbWUiLCJsYXN0TmFtZSJdLCJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJGaXJzdCBuYW1lIiwiZGVmYXVsdCI6IkNodWNrIn0sImxhc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6Ikxhc3QgbmFtZSJ9LCJhZ2UiOnsidHlwZSI6ImludGVnZXIiLCJ0aXRsZSI6IkFnZSJ9LCJiaW8iOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiQmlvIn0sInBhc3N3b3JkIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlBhc3N3b3JkIiwibWluTGVuZ3RoIjozfSwidGVsZXBob25lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlRlbGVwaG9uZSIsIm1pbkxlbmd0aCI6MTB9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIifSwiYWdlIjp7InVpOndpZGdldCI6InVwZG93biIsInVpOnRpdGxlIjoiQWdlIG9mIHBlcnNvbiIsInVpOmRlc2NyaXB0aW9uIjoiKGVhcnRoaWFuIHllYXIpIn0sImJpbyI6eyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSJ9LCJwYXNzd29yZCI6eyJ1aTp3aWRnZXQiOiJwYXNzd29yZCIsInVpOmhlbHAiOiJIaW50OiBNYWtlIGl0IHN0cm9uZyEifSwiZGF0ZSI6eyJ1aTp3aWRnZXQiOiJhbHQtZGF0ZXRpbWUifSwidGVsZXBob25lIjp7InVpOm9wdGlvbnMiOnsiaW5wdXRUeXBlIjoidGVsIn19fX0=)

Validation error is immediately visible.

#### Expected behavior

Schema can be used without errors.

#### Actual behavior

See description.

### Version

This schema could be used on 1.2.1.

This behaviour (regression?) has been introduced by 1.3.0 and is the same at 1.5.0.

**Comment by sbusch** [comment]
Interestingly, a workaround is to add an `$id` referencing the same schema:

```javascript
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://json-schema.org/draft-06/schema#",
  // ...
}
```

[Example on RJSF playground](https://mozilla-services.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJmaXJzdE5hbWUiOiJDaHVjayIsImxhc3ROYW1lIjoiTm9ycmlzIiwiYWdlIjo3NSwiYmlvIjoiUm91bmRob3VzZSBraWNraW5nIGFzc2VzIHNpbmNlIDE5NDAiLCJwYXNzd29yZCI6Im5vbmVlZCJ9LCJzY2hlbWEiOnsiJHNjaGVtYSI6Imh0dHA6Ly9qc29uLXNjaGVtYS5vcmcvZHJhZnQtMDYvc2NoZW1hIyIsIiRpZCI6Imh0dHA6Ly9qc29uLXNjaGVtYS5vcmcvZHJhZnQtMDYvc2NoZW1hIyIsInRpdGxlIjoiQSByZWdpc3RyYXRpb24gZm9ybSIsImRlc2NyaXB0aW9uIjoiQSBzaW1wbGUgZm9ybSBleGFtcGxlLiIsInR5cGUiOiJvYmplY3QiLCJyZXF1aXJlZCI6WyJmaXJzdE5hbWUiLCJsYXN0TmFtZSJdLCJwcm9wZXJ0aWVzIjp7ImZpcnN0TmFtZSI6eyJ0eXBlIjoic3RyaW5nIiwidGl0bGUiOiJGaXJzdCBuYW1lIiwiZGVmYXVsdCI6IkNodWNrIn0sImxhc3ROYW1lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6Ikxhc3QgbmFtZSJ9LCJhZ2UiOnsidHlwZSI6ImludGVnZXIiLCJ0aXRsZSI6IkFnZSJ9LCJiaW8iOnsidHlwZSI6InN0cmluZyIsInRpdGxlIjoiQmlvIn0sInBhc3N3b3JkIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlBhc3N3b3JkIiwibWluTGVuZ3RoIjozfSwidGVsZXBob25lIjp7InR5cGUiOiJzdHJpbmciLCJ0aXRsZSI6IlRlbGVwaG9uZSIsIm1pbkxlbmd0aCI6MTB9fX0sInVpU2NoZW1hIjp7ImZpcnN0TmFtZSI6eyJ1aTphdXRvZm9jdXMiOnRydWUsInVpOmVtcHR5VmFsdWUiOiIifSwiYWdlIjp7InVpOndpZGdldCI6InVwZG93biIsInVpOnRpdGxlIjoiQWdlIG9mIHBlcnNvbiIsInVpOmRlc2NyaXB0aW9uIjoiKGVhcnRoaWFuIHllYXIpIn0sImJpbyI6eyJ1aTp3aWRnZXQiOiJ0ZXh0YXJlYSJ9LCJwYXNzd29yZCI6eyJ1aTp3aWRnZXQiOiJwYXNzd29yZCIsInVpOmhlbHAiOiJIaW50OiBNYWtlIGl0IHN0cm9uZyEifSwiZGF0ZSI6eyJ1aTp3aWRnZXQiOiJhbHQtZGF0ZXRpbWUifSwidGVsZXBob25lIjp7InVpOm9wdGlvbnMiOnsiaW5wdXRUeXBlIjoidGVsIn19fX0=)

Without checking the code i think `$id` overrides `$schema`, and seems to be handled correctly (= not triggering the wrong validation error) in contrast with `$schema`.

In case of an **invalid** schema in `$id`, the `$id`key is seemingly ignored and the error resurfaces again.

**Comment by sbusch** [comment]
Ok, got it, I had to define a [Custom schema validation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/docs/validation.md#custom-schema-validation):

    To have your schemas validated against any other meta schema than
    draft-07 (the current version of [JSON Schema](http://json-schema.org/)),
    make sure your schema has a `$schema` attribute that enables the validator
    to use the correct meta schema. For example: ...

Introduced at #1130

@epicfaace some remarks:

* `1.3.0` was a potentially breaking release. Does the project follow [semantic versioning](https://semver.org/)?
* if the default "draft-07" comes implicitly from ajv, it's better to import and assign it explicitly -> more control over such breaking changes
* <http://react-jsonschema-form.readthedocs.io/> is quite outdated, is that known?
* the way the example for defining a custom schema validation is implemented forces a re-rendering of the form each time the parent re-renders (because a new array is constructed every time). The example could stay simple, but this should be at least noted for the copy pasta crowd :-)

**Comment by epicfaace** [comment]
@sbusch I didn't realize #1130 was a breaking change -- what part of it would you say makes it a breaking change?

**Comment by laspluviosillas** [comment]
Not sure if this is related, but when trying to make this library work with AJV 6.7.0 (React 16.8.4) 
importing "Form" from "react-jsonschema-form"; causes Webpack to fail compilation with the following error:

> Module build failed (from ./node_modules/babel-loader/lib/index.js):
> /SyntaxError: /Users/jstrong/webapps/rails/eebos_rails/node_modules/ajv/lib/refs/json-schema-draft-07.json: Unexpected token, expected ";" (2:13)
> ...
>  @ ./node_modules/ajv/lib/ajv.js 488:19-62
> @ ./node_modules/react-jsonschema-form/lib/validate.js

**Comment by epicfaace** [comment]
@laspluviosillas sounds like a problem with your webpack config? if you can send me a link to your github repo I can help look into it

**Comment by khateeb82** [comment]
> AJV 6.7.0
 how to solve this issue?
