### ISSUE TITLE
ANNOUNCEMENT: Breaking changes planned for v3

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#2297]
The next version of rjsf will be v3, and we'll add a few breaking changes to it.

## Planned changes
PRs that are nearly ready and will be added in v3:
- [ ] refactor: types for withTheme #2279
- [x] No core-js in core #2211
- [x] Drop support for node 8 / 9 #2031
- [x] Drop support for node 10 #2299
- [ ] Maintain AJV properties when custom validator is in use. #2002

## Other potential changes
If someone makes PRs for these issues, we might be able to get them into v3.
- noHtml5Validate should be true by default #1184
- Fieldset preventing flexbox styling #762

These PRs would be good to add, but still have some work to do on them:
- support if/then/else, breaking change is removing the dependency on `json-schema-merge-allof` https://github.com/rjsf-team/react-jsonschema-form/pull/1666

Have suggestions for changes / additional items we should add to this list? Feedback welcome!

cc @ri0ter @erunion @stanlemon @mattcosta7 @zepatrik @wegry @jimmycallin @robophred @bmmpt

**Comment by wegry** [comment]
@epicfaace I was hoping the react-is bump might make it into v3 as well. https://github.com/rjsf-team/react-jsonschema-form/pull/2196.

**Comment by epicfaace** [comment]
Oh, is that a breaking change? If not, we can still get it in either in v3 or sometime later, but the scope of this issue is just categorizing the breaking changes (because they _have_ to be released on a new major bump).

**Comment by wegry** [comment]
Sounds good.

> Is that a breaking change?

I don't believe so. Just something I've been hankering for.

**Comment by mattcosta7** [comment]
@epicfaace sounds good to me. 

I noticed there's a few things tagged with 'deprecated' in the codebase.  might be a good time to clean those as well.

Particularly
* autocomplete vs autoComplete 
*  `ui:widget` object API, where a widget and options were specified with `"ui:widget": {component, options}` shape

**Comment by jimmycallin** [comment]
Sounds good! Might want to look into the discussions in this PR and consider them as well https://github.com/rjsf-team/react-jsonschema-form/pull/2010

**Comment by stanlemon** [comment]
Some thoughts...
- Previously we discussed swapping out native controls in the Material UI theme for their provided ones, specifically the date picker.
- Any widget built around arrays and nesting requires a lot of work in a new theme, it would be great if to make that a lighter lift.
- This might be controversial, but perhaps we drop the verbose date picker with tons of selects altogether.

**Comment by jimmycallin** [comment]
@epicfaace You also mentioned this old PR of mine to be a breaking change https://github.com/rjsf-team/react-jsonschema-form/pull/1522

might be time to merge it then (or let me know if you want me to revert the breaking change part). personally i would love to see rjsf to be [strict mode valid](https://reactjs.org/docs/strict-mode.html) as a part of v3.

**Comment by gsstar9028** [comment]
@epicfaace Please consider including https://github.com/rjsf-team/react-jsonschema-form/pull/2272

**Comment by epicfaace** [comment]
@gsstar9028 no worries, it's already been merged into master, so it will be included!

**Comment by epicfaace** [comment]
> personally i would love to see rjsf to be [strict mode valid](https://reactjs.org/docs/strict-mode.html) as a part of v3.

@jimmycallin Agreed, that would be nice! (so we'd need to stop using unsafe component lifecycle methods) Sorry for the delay in responding to your other PR.

**Comment by xyy7260** [comment]
V3 version, how soon to release。

**Comment by epicfaace** [comment]
It's been quite a while since I made this post, so I'm going to go ahead and release v3 soon so we don't have too much time lag between versions. We can release the other pending breaking changes in v4 (which could probably come relatively soon after v3 and have less breaking changes).

**Comment by heath-freenome** [comment]
Is there going to be support for the JSON Schema v7 conditionals? https://json-schema.org/understanding-json-schema/reference/conditionals.html

**Comment by epicfaace** [comment]
Not now, but maybe we can track that in another issue.

**Comment by heath-freenome** [comment]
That would be awesome because our implementation might be forced to use it given some constraints we have.

**Comment by heath-freenome** [comment]
> Not now, but maybe we can track that in another issue.
That would be awesome because we might be forced to use it in our schema given some constraints we have

**Comment by wegry** [comment]
@epicfaace do you need any help with anything prior to v3 going out? I'd like to help carry this over the hump if possible.

**Comment by epicfaace** [comment]
@wegry Thanks for checking. I'd like to clean up https://github.com/rjsf-team/react-jsonschema-form/blob/master/docs/3.x%20upgrade%20guide.md (ensure that the tone is consistent, everything is clear, etc.) before release because multiple people have added to it and it doesn't read very well at the moment.

**Comment by epicfaace** [comment]
Thanks for your help @wegry !

v3 is now out! Migrated the pending issues to https://github.com/rjsf-team/react-jsonschema-form/issues/2437.
