### ISSUE TITLE
ANNOUNCEMENT: Breaking changes planned for v4

### ISSUE THREAD

**Issue by epicfaace** [rjsf-team/react-jsonschema-form#2437]
The next version of rjsf will be v4. I'm going to start making a running issue like this for each breaking change so it's easier to organize what we want to get in for each major release version.

## Planned breaking changes
PRs that are nearly ready and will hopefully be added in v4:
- [ ] refactor: types for withTheme #2279
- [ ] Maintain AJV properties when custom validator is in use. #2002
- [ ] Remove componentWillReceiveProps from Form.jsx #2010

## Other potential changes
If someone makes PRs for these issues, we might be able to get them into v3.
- noHtml5Validate should be true by default #1184
- Fieldset preventing flexbox styling #762

These PRs would be good to add, but still have some work to do on them:
- support if/then/else, breaking change is removing the dependency on `json-schema-merge-allof` https://github.com/rjsf-team/react-jsonschema-form/pull/2466

Have suggestions for changes / additional items we should add to this list? Feedback welcome!

cc @ri0ter @erunion @stanlemon @mattcosta7 @zepatrik @wegry @jimmycallin @robophred @bmmpt

**Comment by jimmycallin** [comment]
Great job with the v3 release!

I think my comments from the last PR still stands regarding react strict mode, which is related to this PR and its discussions https://github.com/rjsf-team/react-jsonschema-form/pull/2010

**Comment by epicfaace** [comment]
Okay, added it to the list!

**Comment by xgenvn** [comment]
Is it possible to separate the parser logic (in core) into a subpackage? I know the `r` is for `react`, but if we make the core more generic, I think it's easy to implement in another framework.

**Comment by epicfaace** [comment]
Which kind of logic are you referring to?

--
Ashwin Ramaswami

**Comment by xgenvn** [comment]
@epicfaace Hi, I refer to the parser from JSONSchema (model) and UI Schema into abstract inputs/controls. I'm kind of Vue-guy, and there is no match implementation for JSONSchema-based form rendering. If there is an abstract layer for the view and reactive state, it's possible to add Vue support as well.

**Comment by epicfaace** [comment]
That's a good idea. Is this something whose design / code you'd be willing
to contribute?

--
Ashwin Ramaswami

**Comment by xgenvn** [comment]
@epicfaace I think I can contribute to this if it's getting more attention. At the moment I'm referencing the schema for a Vue implementation. I guess the parsing part will be similar.

**Comment by epicfaace** [comment]
Yes, that would be great! Do you want to maybe outline a design for this in
a design doc (maybe Google Docs) so we can figure out the best way to go
about this?

--
Ashwin Ramaswami

**Comment by xgenvn** [comment]
@epicfaace I will spend some time digging into the current implementation first and will try to outline the design. I think for in-depth discussion, we can continue on Discord. Thanks for hearing the idea!

**Comment by ssbyoung** [comment]
Not sure if https://github.com/rjsf-team/react-jsonschema-form/pull/2456 is worth considering for this release or the next one.

**Comment by tm1000** [comment]
What about hooks support? EG rewriting the class components to be functional hook components instead

**Comment by Zakhar-Kutsko** [comment]
Hi there! When you plan to release a new version?

**Comment by epicfaace** [comment]
This Friday

--
Ashwin Ramaswami
